// Autogenerated Go message buffer code.
// Source: clad/cloud/common.clad
// Full command line: victor-clad/tools/message-buffers/emitters/Go_emitter.py -C src -o generated/cladgo/src clad/cloud/common.clad

package cloud

import (
	"bytes"
)

// STRUCTURE Void
type Void struct {
}

func (v *Void) Size() uint32 {
	return 0
}

func (v *Void) Unpack(buf *bytes.Buffer) error {
	return nil
}

func (v *Void) Pack(buf *bytes.Buffer) error {
	return nil
}

func (v *Void) String() string {
	return ""
}
