// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response_status.proto

package Anki_Vector_external_interface

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseStatus_StatusCode int32

const (
	ResponseStatus_UNKNOWN ResponseStatus_StatusCode = 0
	// The message has completed as expected.
	ResponseStatus_RESPONSE_RECEIVED ResponseStatus_StatusCode = 1
	// The message has been sent to the robot.
	ResponseStatus_REQUEST_PROCESSING ResponseStatus_StatusCode = 2
	// The message has been handled successfully at the interface level.
	ResponseStatus_OK ResponseStatus_StatusCode = 3
	// The user was not authorizied.
	ResponseStatus_FORBIDDEN ResponseStatus_StatusCode = 100
	// The requested attribute was not found.
	ResponseStatus_NOT_FOUND ResponseStatus_StatusCode = 101
	// Currently updating values from another call.
	ResponseStatus_ERROR_UPDATE_IN_PROGRESS ResponseStatus_StatusCode = 102
)

var ResponseStatus_StatusCode_name = map[int32]string{
	0:   "UNKNOWN",
	1:   "RESPONSE_RECEIVED",
	2:   "REQUEST_PROCESSING",
	3:   "OK",
	100: "FORBIDDEN",
	101: "NOT_FOUND",
	102: "ERROR_UPDATE_IN_PROGRESS",
}
var ResponseStatus_StatusCode_value = map[string]int32{
	"UNKNOWN":                  0,
	"RESPONSE_RECEIVED":        1,
	"REQUEST_PROCESSING":       2,
	"OK":                       3,
	"FORBIDDEN":                100,
	"NOT_FOUND":                101,
	"ERROR_UPDATE_IN_PROGRESS": 102,
}

func (x ResponseStatus_StatusCode) String() string {
	return proto.EnumName(ResponseStatus_StatusCode_name, int32(x))
}
func (ResponseStatus_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_status_2925313abb87c493, []int{0, 0}
}

// A shared response message sent back as part of most requests.
// This will indicate the generic state of the request.
type ResponseStatus struct {
	// The generic status code to give high-level insight into the progress of a given message.
	Code                 ResponseStatus_StatusCode `protobuf:"varint,1,opt,name=code,enum=Anki.Vector.external_interface.ResponseStatus_StatusCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ResponseStatus) Reset()         { *m = ResponseStatus{} }
func (m *ResponseStatus) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus) ProtoMessage()    {}
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_status_2925313abb87c493, []int{0}
}
func (m *ResponseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStatus.Unmarshal(m, b)
}
func (m *ResponseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStatus.Marshal(b, m, deterministic)
}
func (dst *ResponseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStatus.Merge(dst, src)
}
func (m *ResponseStatus) XXX_Size() int {
	return xxx_messageInfo_ResponseStatus.Size(m)
}
func (m *ResponseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStatus proto.InternalMessageInfo

func (m *ResponseStatus) GetCode() ResponseStatus_StatusCode {
	if m != nil {
		return m.Code
	}
	return ResponseStatus_UNKNOWN
}

func init() {
	proto.RegisterType((*ResponseStatus)(nil), "Anki.Vector.external_interface.ResponseStatus")
	proto.RegisterEnum("Anki.Vector.external_interface.ResponseStatus_StatusCode", ResponseStatus_StatusCode_name, ResponseStatus_StatusCode_value)
}

func init() {
	proto.RegisterFile("response_status.proto", fileDescriptor_response_status_2925313abb87c493)
}

var fileDescriptor_response_status_2925313abb87c493 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x45, 0x4d, 0x95, 0x8a, 0x4f, 0x2c, 0xe3, 0x40, 0xa5, 0x0b, 0x11, 0xe9, 0xca, 0xd5, 0x2c,
	0x74, 0xe5, 0xb2, 0x26, 0xaf, 0x25, 0x14, 0x67, 0xe2, 0x9b, 0xa4, 0x2e, 0x87, 0x98, 0xbc, 0x42,
	0x51, 0x32, 0x25, 0x19, 0xc1, 0x8f, 0xf0, 0x5b, 0xfd, 0x06, 0x69, 0x14, 0xc4, 0x4d, 0x57, 0x97,
	0x7b, 0xe1, 0x9c, 0xc5, 0x85, 0x71, 0xcb, 0xdd, 0xd6, 0x37, 0x1d, 0xbb, 0x2e, 0x94, 0xe1, 0xbd,
	0x53, 0xdb, 0xd6, 0x07, 0x2f, 0xaf, 0x66, 0xcd, 0xeb, 0x46, 0xad, 0xb8, 0x0a, 0xbe, 0x55, 0xfc,
	0x11, 0xb8, 0x6d, 0xca, 0x37, 0xb7, 0x69, 0x02, 0xb7, 0xeb, 0xb2, 0xe2, 0xe9, 0x57, 0x04, 0x23,
	0xfa, 0x25, 0x6d, 0x0f, 0xca, 0x47, 0x38, 0xaa, 0x7c, 0xcd, 0x93, 0xe8, 0x3a, 0xba, 0x19, 0xdd,
	0xde, 0xab, 0xfd, 0x06, 0xf5, 0x9f, 0x56, 0x3f, 0x11, 0xfb, 0x9a, 0xa9, 0xd7, 0x4c, 0x3f, 0x23,
	0x80, 0xbf, 0x51, 0x9e, 0xc2, 0x71, 0xa1, 0x97, 0xda, 0x3c, 0x6b, 0x71, 0x20, 0xc7, 0x70, 0x4e,
	0x68, 0x33, 0xa3, 0x2d, 0x3a, 0xc2, 0x18, 0xd3, 0x15, 0x26, 0x22, 0x92, 0x17, 0x20, 0x09, 0x9f,
	0x0a, 0xb4, 0xb9, 0xcb, 0xc8, 0xc4, 0x68, 0x6d, 0xaa, 0x17, 0x62, 0x20, 0x87, 0x30, 0x30, 0x4b,
	0x71, 0x28, 0xcf, 0xe0, 0x64, 0x6e, 0xe8, 0x21, 0x4d, 0x12, 0xd4, 0xa2, 0xde, 0x55, 0x6d, 0x72,
	0x37, 0x37, 0x85, 0x4e, 0x04, 0xcb, 0x4b, 0x98, 0x20, 0x91, 0x21, 0x57, 0x64, 0xc9, 0x2c, 0x47,
	0x97, 0xea, 0x9d, 0x65, 0x41, 0x68, 0xad, 0x58, 0xbf, 0x0c, 0xfb, 0x5f, 0xee, 0xbe, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0x04, 0x41, 0x13, 0x30, 0x01, 0x00, 0x00,
}
