// Code generated by protoc-gen-go. DO NOT EDIT.
// source: settings.proto

package Anki_Vector_external_interface

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApiVersion int32

const (
	ApiVersion_INVALID ApiVersion = 0
	ApiVersion_LATEST  ApiVersion = 1
)

var ApiVersion_name = map[int32]string{
	0: "INVALID",
	1: "LATEST",
}
var ApiVersion_value = map[string]int32{
	"INVALID": 0,
	"LATEST":  1,
}

func (x ApiVersion) String() string {
	return proto.EnumName(ApiVersion_name, int32(x))
}
func (ApiVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{0}
}

type Volume int32

const (
	Volume_MUTE        Volume = 0
	Volume_LOW         Volume = 1
	Volume_MEDIUM_LOW  Volume = 2
	Volume_MEDIUM      Volume = 3
	Volume_MEDIUM_HIGH Volume = 4
	Volume_HIGH        Volume = 5
)

var Volume_name = map[int32]string{
	0: "MUTE",
	1: "LOW",
	2: "MEDIUM_LOW",
	3: "MEDIUM",
	4: "MEDIUM_HIGH",
	5: "HIGH",
}
var Volume_value = map[string]int32{
	"MUTE":        0,
	"LOW":         1,
	"MEDIUM_LOW":  2,
	"MEDIUM":      3,
	"MEDIUM_HIGH": 4,
	"HIGH":        5,
}

func (x Volume) String() string {
	return proto.EnumName(Volume_name, int32(x))
}
func (Volume) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{1}
}

type JdocType int32

const (
	JdocType_ROBOT_SETTINGS       JdocType = 0
	JdocType_ROBOT_LIFETIME_STATS JdocType = 1
	JdocType_ACCOUNT_SETTINGS     JdocType = 2
	JdocType_USER_ENTITLEMENTS    JdocType = 3
)

var JdocType_name = map[int32]string{
	0: "ROBOT_SETTINGS",
	1: "ROBOT_LIFETIME_STATS",
	2: "ACCOUNT_SETTINGS",
	3: "USER_ENTITLEMENTS",
}
var JdocType_value = map[string]int32{
	"ROBOT_SETTINGS":       0,
	"ROBOT_LIFETIME_STATS": 1,
	"ACCOUNT_SETTINGS":     2,
	"USER_ENTITLEMENTS":    3,
}

func (x JdocType) String() string {
	return proto.EnumName(JdocType_name, int32(x))
}
func (JdocType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{2}
}

type JdocResolveMethod int32

const (
	JdocResolveMethod_PUSH_TO_CLOUD   JdocResolveMethod = 0
	JdocResolveMethod_PULL_FROM_CLOUD JdocResolveMethod = 1
)

var JdocResolveMethod_name = map[int32]string{
	0: "PUSH_TO_CLOUD",
	1: "PULL_FROM_CLOUD",
}
var JdocResolveMethod_value = map[string]int32{
	"PUSH_TO_CLOUD":   0,
	"PULL_FROM_CLOUD": 1,
}

func (x JdocResolveMethod) String() string {
	return proto.EnumName(JdocResolveMethod_name, int32(x))
}
func (JdocResolveMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{3}
}

// RobotSetting enum values are not in all caps for historical reasons.
// Changing that now would involve a format migration because we're now
// saving robot settings jdocs in the cloud.
type RobotSetting int32

const (
	RobotSetting_clock_24_hour      RobotSetting = 0
	RobotSetting_eye_color          RobotSetting = 1
	RobotSetting_custom_eye_color   RobotSetting = 2
	RobotSetting_default_location   RobotSetting = 3
	RobotSetting_dist_is_metric     RobotSetting = 4
	RobotSetting_locale             RobotSetting = 5
	RobotSetting_master_volume      RobotSetting = 6
	RobotSetting_temp_is_fahrenheit RobotSetting = 7
	RobotSetting_time_zone          RobotSetting = 8
	RobotSetting_button_wakeword    RobotSetting = 9
)

var RobotSetting_name = map[int32]string{
	0: "clock_24_hour",
	1: "eye_color",
	2: "custom_eye_color",
	3: "default_location",
	4: "dist_is_metric",
	5: "locale",
	6: "master_volume",
	7: "temp_is_fahrenheit",
	8: "time_zone",
	9: "button_wakeword",
}
var RobotSetting_value = map[string]int32{
	"clock_24_hour":      0,
	"eye_color":          1,
	"custom_eye_color":   2,
	"default_location":   3,
	"dist_is_metric":     4,
	"locale":             5,
	"master_volume":      6,
	"temp_is_fahrenheit": 7,
	"time_zone":          8,
	"button_wakeword":    9,
}

func (x RobotSetting) String() string {
	return proto.EnumName(RobotSetting_name, int32(x))
}
func (RobotSetting) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{4}
}

type EyeColor int32

const (
	EyeColor_TIP_OVER_TEAL          EyeColor = 0
	EyeColor_OVERFIT_ORANGE         EyeColor = 1
	EyeColor_UNCANNY_YELLOW         EyeColor = 2
	EyeColor_NON_LINEAR_LIME        EyeColor = 3
	EyeColor_SINGULARITY_SAPPHIRE   EyeColor = 4
	EyeColor_FALSE_POSITIVE_PURPLE  EyeColor = 5
	EyeColor_CONFUSION_MATRIX_GREEN EyeColor = 6
)

var EyeColor_name = map[int32]string{
	0: "TIP_OVER_TEAL",
	1: "OVERFIT_ORANGE",
	2: "UNCANNY_YELLOW",
	3: "NON_LINEAR_LIME",
	4: "SINGULARITY_SAPPHIRE",
	5: "FALSE_POSITIVE_PURPLE",
	6: "CONFUSION_MATRIX_GREEN",
}
var EyeColor_value = map[string]int32{
	"TIP_OVER_TEAL":          0,
	"OVERFIT_ORANGE":         1,
	"UNCANNY_YELLOW":         2,
	"NON_LINEAR_LIME":        3,
	"SINGULARITY_SAPPHIRE":   4,
	"FALSE_POSITIVE_PURPLE":  5,
	"CONFUSION_MATRIX_GREEN": 6,
}

func (x EyeColor) String() string {
	return proto.EnumName(EyeColor_name, int32(x))
}
func (EyeColor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{5}
}

type ButtonWakeWord int32

const (
	ButtonWakeWord_BUTTON_WAKEWORD_HEY_VECTOR ButtonWakeWord = 0
	ButtonWakeWord_BUTTON_WAKEWORD_ALEXA      ButtonWakeWord = 1
)

var ButtonWakeWord_name = map[int32]string{
	0: "BUTTON_WAKEWORD_HEY_VECTOR",
	1: "BUTTON_WAKEWORD_ALEXA",
}
var ButtonWakeWord_value = map[string]int32{
	"BUTTON_WAKEWORD_HEY_VECTOR": 0,
	"BUTTON_WAKEWORD_ALEXA":      1,
}

func (x ButtonWakeWord) String() string {
	return proto.EnumName(ButtonWakeWord_name, int32(x))
}
func (ButtonWakeWord) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{6}
}

type AccountSetting int32

const (
	AccountSetting_DATA_COLLECTION AccountSetting = 0
	AccountSetting_APP_LOCALE      AccountSetting = 1
)

var AccountSetting_name = map[int32]string{
	0: "DATA_COLLECTION",
	1: "APP_LOCALE",
}
var AccountSetting_value = map[string]int32{
	"DATA_COLLECTION": 0,
	"APP_LOCALE":      1,
}

func (x AccountSetting) String() string {
	return proto.EnumName(AccountSetting_name, int32(x))
}
func (AccountSetting) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{7}
}

type UserEntitlement int32

const (
	UserEntitlement_KICKSTARTER_EYES UserEntitlement = 0
)

var UserEntitlement_name = map[int32]string{
	0: "KICKSTARTER_EYES",
}
var UserEntitlement_value = map[string]int32{
	"KICKSTARTER_EYES": 0,
}

func (x UserEntitlement) String() string {
	return proto.EnumName(UserEntitlement_name, int32(x))
}
func (UserEntitlement) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{8}
}

type ResultCode int32

const (
	ResultCode_SETTINGS_ACCEPTED        ResultCode = 0
	ResultCode_ERROR_UPDATE_IN_PROGRESS ResultCode = 1
)

var ResultCode_name = map[int32]string{
	0: "SETTINGS_ACCEPTED",
	1: "ERROR_UPDATE_IN_PROGRESS",
}
var ResultCode_value = map[string]int32{
	"SETTINGS_ACCEPTED":        0,
	"ERROR_UPDATE_IN_PROGRESS": 1,
}

func (x ResultCode) String() string {
	return proto.EnumName(ResultCode_name, int32(x))
}
func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{9}
}

type CustomEyeColor struct {
	Hue                  float32  `protobuf:"fixed32,1,opt,name=hue" json:"hue,omitempty"`
	Saturation           float32  `protobuf:"fixed32,2,opt,name=saturation" json:"saturation,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomEyeColor) Reset()         { *m = CustomEyeColor{} }
func (m *CustomEyeColor) String() string { return proto.CompactTextString(m) }
func (*CustomEyeColor) ProtoMessage()    {}
func (*CustomEyeColor) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{0}
}
func (m *CustomEyeColor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomEyeColor.Unmarshal(m, b)
}
func (m *CustomEyeColor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomEyeColor.Marshal(b, m, deterministic)
}
func (dst *CustomEyeColor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomEyeColor.Merge(dst, src)
}
func (m *CustomEyeColor) XXX_Size() int {
	return xxx_messageInfo_CustomEyeColor.Size(m)
}
func (m *CustomEyeColor) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomEyeColor.DiscardUnknown(m)
}

var xxx_messageInfo_CustomEyeColor proto.InternalMessageInfo

func (m *CustomEyeColor) GetHue() float32 {
	if m != nil {
		return m.Hue
	}
	return 0
}

func (m *CustomEyeColor) GetSaturation() float32 {
	if m != nil {
		return m.Saturation
	}
	return 0
}

func (m *CustomEyeColor) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type RobotSettingsConfig struct {
	// Types that are valid to be assigned to OneofClock_24Hour:
	//	*RobotSettingsConfig_Clock_24Hour
	OneofClock_24Hour isRobotSettingsConfig_OneofClock_24Hour `protobuf_oneof:"oneof_clock_24_hour"`
	// Types that are valid to be assigned to OneofEyeColor:
	//	*RobotSettingsConfig_EyeColor
	OneofEyeColor isRobotSettingsConfig_OneofEyeColor `protobuf_oneof:"oneof_eye_color"`
	// Types that are valid to be assigned to OneofCustomEyeColor:
	//	*RobotSettingsConfig_CustomEyeColor
	OneofCustomEyeColor isRobotSettingsConfig_OneofCustomEyeColor `protobuf_oneof:"oneof_custom_eye_color"`
	// Types that are valid to be assigned to OneofDefaultLocation:
	//	*RobotSettingsConfig_DefaultLocation
	OneofDefaultLocation isRobotSettingsConfig_OneofDefaultLocation `protobuf_oneof:"oneof_default_location"`
	// Types that are valid to be assigned to OneofDistIsMetric:
	//	*RobotSettingsConfig_DistIsMetric
	OneofDistIsMetric isRobotSettingsConfig_OneofDistIsMetric `protobuf_oneof:"oneof_dist_is_metric"`
	// Types that are valid to be assigned to OneofLocale:
	//	*RobotSettingsConfig_Locale
	OneofLocale isRobotSettingsConfig_OneofLocale `protobuf_oneof:"oneof_locale"`
	// Types that are valid to be assigned to OneofMasterVolume:
	//	*RobotSettingsConfig_MasterVolume
	OneofMasterVolume isRobotSettingsConfig_OneofMasterVolume `protobuf_oneof:"oneof_master_volume"`
	// Types that are valid to be assigned to OneofTempIsFahrenheit:
	//	*RobotSettingsConfig_TempIsFahrenheit
	OneofTempIsFahrenheit isRobotSettingsConfig_OneofTempIsFahrenheit `protobuf_oneof:"oneof_temp_is_fahrenheit"`
	// Types that are valid to be assigned to OneofTimeZone:
	//	*RobotSettingsConfig_TimeZone
	OneofTimeZone isRobotSettingsConfig_OneofTimeZone `protobuf_oneof:"oneof_time_zone"`
	// Types that are valid to be assigned to OneofButtonWakeword:
	//	*RobotSettingsConfig_ButtonWakeword
	OneofButtonWakeword  isRobotSettingsConfig_OneofButtonWakeword `protobuf_oneof:"oneof_button_wakeword"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *RobotSettingsConfig) Reset()         { *m = RobotSettingsConfig{} }
func (m *RobotSettingsConfig) String() string { return proto.CompactTextString(m) }
func (*RobotSettingsConfig) ProtoMessage()    {}
func (*RobotSettingsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{1}
}
func (m *RobotSettingsConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotSettingsConfig.Unmarshal(m, b)
}
func (m *RobotSettingsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotSettingsConfig.Marshal(b, m, deterministic)
}
func (dst *RobotSettingsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotSettingsConfig.Merge(dst, src)
}
func (m *RobotSettingsConfig) XXX_Size() int {
	return xxx_messageInfo_RobotSettingsConfig.Size(m)
}
func (m *RobotSettingsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotSettingsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RobotSettingsConfig proto.InternalMessageInfo

type isRobotSettingsConfig_OneofClock_24Hour interface {
	isRobotSettingsConfig_OneofClock_24Hour()
}
type isRobotSettingsConfig_OneofEyeColor interface {
	isRobotSettingsConfig_OneofEyeColor()
}
type isRobotSettingsConfig_OneofCustomEyeColor interface {
	isRobotSettingsConfig_OneofCustomEyeColor()
}
type isRobotSettingsConfig_OneofDefaultLocation interface {
	isRobotSettingsConfig_OneofDefaultLocation()
}
type isRobotSettingsConfig_OneofDistIsMetric interface {
	isRobotSettingsConfig_OneofDistIsMetric()
}
type isRobotSettingsConfig_OneofLocale interface {
	isRobotSettingsConfig_OneofLocale()
}
type isRobotSettingsConfig_OneofMasterVolume interface {
	isRobotSettingsConfig_OneofMasterVolume()
}
type isRobotSettingsConfig_OneofTempIsFahrenheit interface {
	isRobotSettingsConfig_OneofTempIsFahrenheit()
}
type isRobotSettingsConfig_OneofTimeZone interface {
	isRobotSettingsConfig_OneofTimeZone()
}
type isRobotSettingsConfig_OneofButtonWakeword interface {
	isRobotSettingsConfig_OneofButtonWakeword()
}

type RobotSettingsConfig_Clock_24Hour struct {
	Clock_24Hour bool `protobuf:"varint,1,opt,name=clock_24_hour,json=clock24Hour,oneof"`
}
type RobotSettingsConfig_EyeColor struct {
	EyeColor EyeColor `protobuf:"varint,2,opt,name=eye_color,json=eyeColor,enum=Anki.Vector.external_interface.EyeColor,oneof"`
}
type RobotSettingsConfig_CustomEyeColor struct {
	CustomEyeColor *CustomEyeColor `protobuf:"bytes,3,opt,name=custom_eye_color,json=customEyeColor,oneof"`
}
type RobotSettingsConfig_DefaultLocation struct {
	DefaultLocation string `protobuf:"bytes,4,opt,name=default_location,json=defaultLocation,oneof"`
}
type RobotSettingsConfig_DistIsMetric struct {
	DistIsMetric bool `protobuf:"varint,5,opt,name=dist_is_metric,json=distIsMetric,oneof"`
}
type RobotSettingsConfig_Locale struct {
	Locale string `protobuf:"bytes,6,opt,name=locale,oneof"`
}
type RobotSettingsConfig_MasterVolume struct {
	MasterVolume Volume `protobuf:"varint,7,opt,name=master_volume,json=masterVolume,enum=Anki.Vector.external_interface.Volume,oneof"`
}
type RobotSettingsConfig_TempIsFahrenheit struct {
	TempIsFahrenheit bool `protobuf:"varint,8,opt,name=temp_is_fahrenheit,json=tempIsFahrenheit,oneof"`
}
type RobotSettingsConfig_TimeZone struct {
	TimeZone string `protobuf:"bytes,9,opt,name=time_zone,json=timeZone,oneof"`
}
type RobotSettingsConfig_ButtonWakeword struct {
	ButtonWakeword ButtonWakeWord `protobuf:"varint,10,opt,name=button_wakeword,json=buttonWakeword,enum=Anki.Vector.external_interface.ButtonWakeWord,oneof"`
}

func (*RobotSettingsConfig_Clock_24Hour) isRobotSettingsConfig_OneofClock_24Hour()         {}
func (*RobotSettingsConfig_EyeColor) isRobotSettingsConfig_OneofEyeColor()                 {}
func (*RobotSettingsConfig_CustomEyeColor) isRobotSettingsConfig_OneofCustomEyeColor()     {}
func (*RobotSettingsConfig_DefaultLocation) isRobotSettingsConfig_OneofDefaultLocation()   {}
func (*RobotSettingsConfig_DistIsMetric) isRobotSettingsConfig_OneofDistIsMetric()         {}
func (*RobotSettingsConfig_Locale) isRobotSettingsConfig_OneofLocale()                     {}
func (*RobotSettingsConfig_MasterVolume) isRobotSettingsConfig_OneofMasterVolume()         {}
func (*RobotSettingsConfig_TempIsFahrenheit) isRobotSettingsConfig_OneofTempIsFahrenheit() {}
func (*RobotSettingsConfig_TimeZone) isRobotSettingsConfig_OneofTimeZone()                 {}
func (*RobotSettingsConfig_ButtonWakeword) isRobotSettingsConfig_OneofButtonWakeword()     {}

func (m *RobotSettingsConfig) GetOneofClock_24Hour() isRobotSettingsConfig_OneofClock_24Hour {
	if m != nil {
		return m.OneofClock_24Hour
	}
	return nil
}
func (m *RobotSettingsConfig) GetOneofEyeColor() isRobotSettingsConfig_OneofEyeColor {
	if m != nil {
		return m.OneofEyeColor
	}
	return nil
}
func (m *RobotSettingsConfig) GetOneofCustomEyeColor() isRobotSettingsConfig_OneofCustomEyeColor {
	if m != nil {
		return m.OneofCustomEyeColor
	}
	return nil
}
func (m *RobotSettingsConfig) GetOneofDefaultLocation() isRobotSettingsConfig_OneofDefaultLocation {
	if m != nil {
		return m.OneofDefaultLocation
	}
	return nil
}
func (m *RobotSettingsConfig) GetOneofDistIsMetric() isRobotSettingsConfig_OneofDistIsMetric {
	if m != nil {
		return m.OneofDistIsMetric
	}
	return nil
}
func (m *RobotSettingsConfig) GetOneofLocale() isRobotSettingsConfig_OneofLocale {
	if m != nil {
		return m.OneofLocale
	}
	return nil
}
func (m *RobotSettingsConfig) GetOneofMasterVolume() isRobotSettingsConfig_OneofMasterVolume {
	if m != nil {
		return m.OneofMasterVolume
	}
	return nil
}
func (m *RobotSettingsConfig) GetOneofTempIsFahrenheit() isRobotSettingsConfig_OneofTempIsFahrenheit {
	if m != nil {
		return m.OneofTempIsFahrenheit
	}
	return nil
}
func (m *RobotSettingsConfig) GetOneofTimeZone() isRobotSettingsConfig_OneofTimeZone {
	if m != nil {
		return m.OneofTimeZone
	}
	return nil
}
func (m *RobotSettingsConfig) GetOneofButtonWakeword() isRobotSettingsConfig_OneofButtonWakeword {
	if m != nil {
		return m.OneofButtonWakeword
	}
	return nil
}

func (m *RobotSettingsConfig) GetClock_24Hour() bool {
	if x, ok := m.GetOneofClock_24Hour().(*RobotSettingsConfig_Clock_24Hour); ok {
		return x.Clock_24Hour
	}
	return false
}

func (m *RobotSettingsConfig) GetEyeColor() EyeColor {
	if x, ok := m.GetOneofEyeColor().(*RobotSettingsConfig_EyeColor); ok {
		return x.EyeColor
	}
	return EyeColor_TIP_OVER_TEAL
}

func (m *RobotSettingsConfig) GetCustomEyeColor() *CustomEyeColor {
	if x, ok := m.GetOneofCustomEyeColor().(*RobotSettingsConfig_CustomEyeColor); ok {
		return x.CustomEyeColor
	}
	return nil
}

func (m *RobotSettingsConfig) GetDefaultLocation() string {
	if x, ok := m.GetOneofDefaultLocation().(*RobotSettingsConfig_DefaultLocation); ok {
		return x.DefaultLocation
	}
	return ""
}

func (m *RobotSettingsConfig) GetDistIsMetric() bool {
	if x, ok := m.GetOneofDistIsMetric().(*RobotSettingsConfig_DistIsMetric); ok {
		return x.DistIsMetric
	}
	return false
}

func (m *RobotSettingsConfig) GetLocale() string {
	if x, ok := m.GetOneofLocale().(*RobotSettingsConfig_Locale); ok {
		return x.Locale
	}
	return ""
}

func (m *RobotSettingsConfig) GetMasterVolume() Volume {
	if x, ok := m.GetOneofMasterVolume().(*RobotSettingsConfig_MasterVolume); ok {
		return x.MasterVolume
	}
	return Volume_MUTE
}

func (m *RobotSettingsConfig) GetTempIsFahrenheit() bool {
	if x, ok := m.GetOneofTempIsFahrenheit().(*RobotSettingsConfig_TempIsFahrenheit); ok {
		return x.TempIsFahrenheit
	}
	return false
}

func (m *RobotSettingsConfig) GetTimeZone() string {
	if x, ok := m.GetOneofTimeZone().(*RobotSettingsConfig_TimeZone); ok {
		return x.TimeZone
	}
	return ""
}

func (m *RobotSettingsConfig) GetButtonWakeword() ButtonWakeWord {
	if x, ok := m.GetOneofButtonWakeword().(*RobotSettingsConfig_ButtonWakeword); ok {
		return x.ButtonWakeword
	}
	return ButtonWakeWord_BUTTON_WAKEWORD_HEY_VECTOR
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RobotSettingsConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RobotSettingsConfig_OneofMarshaler, _RobotSettingsConfig_OneofUnmarshaler, _RobotSettingsConfig_OneofSizer, []interface{}{
		(*RobotSettingsConfig_Clock_24Hour)(nil),
		(*RobotSettingsConfig_EyeColor)(nil),
		(*RobotSettingsConfig_CustomEyeColor)(nil),
		(*RobotSettingsConfig_DefaultLocation)(nil),
		(*RobotSettingsConfig_DistIsMetric)(nil),
		(*RobotSettingsConfig_Locale)(nil),
		(*RobotSettingsConfig_MasterVolume)(nil),
		(*RobotSettingsConfig_TempIsFahrenheit)(nil),
		(*RobotSettingsConfig_TimeZone)(nil),
		(*RobotSettingsConfig_ButtonWakeword)(nil),
	}
}

func _RobotSettingsConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RobotSettingsConfig)
	// oneof_clock_24_hour
	switch x := m.OneofClock_24Hour.(type) {
	case *RobotSettingsConfig_Clock_24Hour:
		t := uint64(0)
		if x.Clock_24Hour {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("RobotSettingsConfig.OneofClock_24Hour has unexpected type %T", x)
	}
	// oneof_eye_color
	switch x := m.OneofEyeColor.(type) {
	case *RobotSettingsConfig_EyeColor:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.EyeColor))
	case nil:
	default:
		return fmt.Errorf("RobotSettingsConfig.OneofEyeColor has unexpected type %T", x)
	}
	// oneof_custom_eye_color
	switch x := m.OneofCustomEyeColor.(type) {
	case *RobotSettingsConfig_CustomEyeColor:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CustomEyeColor); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RobotSettingsConfig.OneofCustomEyeColor has unexpected type %T", x)
	}
	// oneof_default_location
	switch x := m.OneofDefaultLocation.(type) {
	case *RobotSettingsConfig_DefaultLocation:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.DefaultLocation)
	case nil:
	default:
		return fmt.Errorf("RobotSettingsConfig.OneofDefaultLocation has unexpected type %T", x)
	}
	// oneof_dist_is_metric
	switch x := m.OneofDistIsMetric.(type) {
	case *RobotSettingsConfig_DistIsMetric:
		t := uint64(0)
		if x.DistIsMetric {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("RobotSettingsConfig.OneofDistIsMetric has unexpected type %T", x)
	}
	// oneof_locale
	switch x := m.OneofLocale.(type) {
	case *RobotSettingsConfig_Locale:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Locale)
	case nil:
	default:
		return fmt.Errorf("RobotSettingsConfig.OneofLocale has unexpected type %T", x)
	}
	// oneof_master_volume
	switch x := m.OneofMasterVolume.(type) {
	case *RobotSettingsConfig_MasterVolume:
		b.EncodeVarint(7<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.MasterVolume))
	case nil:
	default:
		return fmt.Errorf("RobotSettingsConfig.OneofMasterVolume has unexpected type %T", x)
	}
	// oneof_temp_is_fahrenheit
	switch x := m.OneofTempIsFahrenheit.(type) {
	case *RobotSettingsConfig_TempIsFahrenheit:
		t := uint64(0)
		if x.TempIsFahrenheit {
			t = 1
		}
		b.EncodeVarint(8<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("RobotSettingsConfig.OneofTempIsFahrenheit has unexpected type %T", x)
	}
	// oneof_time_zone
	switch x := m.OneofTimeZone.(type) {
	case *RobotSettingsConfig_TimeZone:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.TimeZone)
	case nil:
	default:
		return fmt.Errorf("RobotSettingsConfig.OneofTimeZone has unexpected type %T", x)
	}
	// oneof_button_wakeword
	switch x := m.OneofButtonWakeword.(type) {
	case *RobotSettingsConfig_ButtonWakeword:
		b.EncodeVarint(10<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.ButtonWakeword))
	case nil:
	default:
		return fmt.Errorf("RobotSettingsConfig.OneofButtonWakeword has unexpected type %T", x)
	}
	return nil
}

func _RobotSettingsConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RobotSettingsConfig)
	switch tag {
	case 1: // oneof_clock_24_hour.clock_24_hour
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofClock_24Hour = &RobotSettingsConfig_Clock_24Hour{x != 0}
		return true, err
	case 2: // oneof_eye_color.eye_color
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofEyeColor = &RobotSettingsConfig_EyeColor{EyeColor(x)}
		return true, err
	case 3: // oneof_custom_eye_color.custom_eye_color
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CustomEyeColor)
		err := b.DecodeMessage(msg)
		m.OneofCustomEyeColor = &RobotSettingsConfig_CustomEyeColor{msg}
		return true, err
	case 4: // oneof_default_location.default_location
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofDefaultLocation = &RobotSettingsConfig_DefaultLocation{x}
		return true, err
	case 5: // oneof_dist_is_metric.dist_is_metric
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofDistIsMetric = &RobotSettingsConfig_DistIsMetric{x != 0}
		return true, err
	case 6: // oneof_locale.locale
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofLocale = &RobotSettingsConfig_Locale{x}
		return true, err
	case 7: // oneof_master_volume.master_volume
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofMasterVolume = &RobotSettingsConfig_MasterVolume{Volume(x)}
		return true, err
	case 8: // oneof_temp_is_fahrenheit.temp_is_fahrenheit
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofTempIsFahrenheit = &RobotSettingsConfig_TempIsFahrenheit{x != 0}
		return true, err
	case 9: // oneof_time_zone.time_zone
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofTimeZone = &RobotSettingsConfig_TimeZone{x}
		return true, err
	case 10: // oneof_button_wakeword.button_wakeword
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofButtonWakeword = &RobotSettingsConfig_ButtonWakeword{ButtonWakeWord(x)}
		return true, err
	default:
		return false, nil
	}
}

func _RobotSettingsConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RobotSettingsConfig)
	// oneof_clock_24_hour
	switch x := m.OneofClock_24Hour.(type) {
	case *RobotSettingsConfig_Clock_24Hour:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// oneof_eye_color
	switch x := m.OneofEyeColor.(type) {
	case *RobotSettingsConfig_EyeColor:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.EyeColor))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// oneof_custom_eye_color
	switch x := m.OneofCustomEyeColor.(type) {
	case *RobotSettingsConfig_CustomEyeColor:
		s := proto.Size(x.CustomEyeColor)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// oneof_default_location
	switch x := m.OneofDefaultLocation.(type) {
	case *RobotSettingsConfig_DefaultLocation:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.DefaultLocation)))
		n += len(x.DefaultLocation)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// oneof_dist_is_metric
	switch x := m.OneofDistIsMetric.(type) {
	case *RobotSettingsConfig_DistIsMetric:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// oneof_locale
	switch x := m.OneofLocale.(type) {
	case *RobotSettingsConfig_Locale:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Locale)))
		n += len(x.Locale)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// oneof_master_volume
	switch x := m.OneofMasterVolume.(type) {
	case *RobotSettingsConfig_MasterVolume:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.MasterVolume))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// oneof_temp_is_fahrenheit
	switch x := m.OneofTempIsFahrenheit.(type) {
	case *RobotSettingsConfig_TempIsFahrenheit:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// oneof_time_zone
	switch x := m.OneofTimeZone.(type) {
	case *RobotSettingsConfig_TimeZone:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.TimeZone)))
		n += len(x.TimeZone)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// oneof_button_wakeword
	switch x := m.OneofButtonWakeword.(type) {
	case *RobotSettingsConfig_ButtonWakeword:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.ButtonWakeword))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type AccountSettingsConfig struct {
	// Types that are valid to be assigned to OneofDataCollection:
	//	*AccountSettingsConfig_DataCollection
	OneofDataCollection isAccountSettingsConfig_OneofDataCollection `protobuf_oneof:"oneof_data_collection"`
	// Types that are valid to be assigned to OneofAppLocale:
	//	*AccountSettingsConfig_AppLocale
	OneofAppLocale       isAccountSettingsConfig_OneofAppLocale `protobuf_oneof:"oneof_app_locale"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *AccountSettingsConfig) Reset()         { *m = AccountSettingsConfig{} }
func (m *AccountSettingsConfig) String() string { return proto.CompactTextString(m) }
func (*AccountSettingsConfig) ProtoMessage()    {}
func (*AccountSettingsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{2}
}
func (m *AccountSettingsConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSettingsConfig.Unmarshal(m, b)
}
func (m *AccountSettingsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSettingsConfig.Marshal(b, m, deterministic)
}
func (dst *AccountSettingsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSettingsConfig.Merge(dst, src)
}
func (m *AccountSettingsConfig) XXX_Size() int {
	return xxx_messageInfo_AccountSettingsConfig.Size(m)
}
func (m *AccountSettingsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSettingsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSettingsConfig proto.InternalMessageInfo

type isAccountSettingsConfig_OneofDataCollection interface {
	isAccountSettingsConfig_OneofDataCollection()
}
type isAccountSettingsConfig_OneofAppLocale interface {
	isAccountSettingsConfig_OneofAppLocale()
}

type AccountSettingsConfig_DataCollection struct {
	DataCollection bool `protobuf:"varint,1,opt,name=data_collection,json=dataCollection,oneof"`
}
type AccountSettingsConfig_AppLocale struct {
	AppLocale string `protobuf:"bytes,2,opt,name=app_locale,json=appLocale,oneof"`
}

func (*AccountSettingsConfig_DataCollection) isAccountSettingsConfig_OneofDataCollection() {}
func (*AccountSettingsConfig_AppLocale) isAccountSettingsConfig_OneofAppLocale()           {}

func (m *AccountSettingsConfig) GetOneofDataCollection() isAccountSettingsConfig_OneofDataCollection {
	if m != nil {
		return m.OneofDataCollection
	}
	return nil
}
func (m *AccountSettingsConfig) GetOneofAppLocale() isAccountSettingsConfig_OneofAppLocale {
	if m != nil {
		return m.OneofAppLocale
	}
	return nil
}

func (m *AccountSettingsConfig) GetDataCollection() bool {
	if x, ok := m.GetOneofDataCollection().(*AccountSettingsConfig_DataCollection); ok {
		return x.DataCollection
	}
	return false
}

func (m *AccountSettingsConfig) GetAppLocale() string {
	if x, ok := m.GetOneofAppLocale().(*AccountSettingsConfig_AppLocale); ok {
		return x.AppLocale
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AccountSettingsConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AccountSettingsConfig_OneofMarshaler, _AccountSettingsConfig_OneofUnmarshaler, _AccountSettingsConfig_OneofSizer, []interface{}{
		(*AccountSettingsConfig_DataCollection)(nil),
		(*AccountSettingsConfig_AppLocale)(nil),
	}
}

func _AccountSettingsConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AccountSettingsConfig)
	// oneof_data_collection
	switch x := m.OneofDataCollection.(type) {
	case *AccountSettingsConfig_DataCollection:
		t := uint64(0)
		if x.DataCollection {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("AccountSettingsConfig.OneofDataCollection has unexpected type %T", x)
	}
	// oneof_app_locale
	switch x := m.OneofAppLocale.(type) {
	case *AccountSettingsConfig_AppLocale:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.AppLocale)
	case nil:
	default:
		return fmt.Errorf("AccountSettingsConfig.OneofAppLocale has unexpected type %T", x)
	}
	return nil
}

func _AccountSettingsConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AccountSettingsConfig)
	switch tag {
	case 1: // oneof_data_collection.data_collection
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofDataCollection = &AccountSettingsConfig_DataCollection{x != 0}
		return true, err
	case 2: // oneof_app_locale.app_locale
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofAppLocale = &AccountSettingsConfig_AppLocale{x}
		return true, err
	default:
		return false, nil
	}
}

func _AccountSettingsConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AccountSettingsConfig)
	// oneof_data_collection
	switch x := m.OneofDataCollection.(type) {
	case *AccountSettingsConfig_DataCollection:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// oneof_app_locale
	switch x := m.OneofAppLocale.(type) {
	case *AccountSettingsConfig_AppLocale:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.AppLocale)))
		n += len(x.AppLocale)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UserEntitlementsConfig struct {
	// Types that are valid to be assigned to OneofKickstarterEyes:
	//	*UserEntitlementsConfig_KickstarterEyes
	OneofKickstarterEyes isUserEntitlementsConfig_OneofKickstarterEyes `protobuf_oneof:"oneof_kickstarter_eyes"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *UserEntitlementsConfig) Reset()         { *m = UserEntitlementsConfig{} }
func (m *UserEntitlementsConfig) String() string { return proto.CompactTextString(m) }
func (*UserEntitlementsConfig) ProtoMessage()    {}
func (*UserEntitlementsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{3}
}
func (m *UserEntitlementsConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEntitlementsConfig.Unmarshal(m, b)
}
func (m *UserEntitlementsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEntitlementsConfig.Marshal(b, m, deterministic)
}
func (dst *UserEntitlementsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEntitlementsConfig.Merge(dst, src)
}
func (m *UserEntitlementsConfig) XXX_Size() int {
	return xxx_messageInfo_UserEntitlementsConfig.Size(m)
}
func (m *UserEntitlementsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEntitlementsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_UserEntitlementsConfig proto.InternalMessageInfo

type isUserEntitlementsConfig_OneofKickstarterEyes interface {
	isUserEntitlementsConfig_OneofKickstarterEyes()
}

type UserEntitlementsConfig_KickstarterEyes struct {
	KickstarterEyes bool `protobuf:"varint,1,opt,name=kickstarter_eyes,json=kickstarterEyes,oneof"`
}

func (*UserEntitlementsConfig_KickstarterEyes) isUserEntitlementsConfig_OneofKickstarterEyes() {}

func (m *UserEntitlementsConfig) GetOneofKickstarterEyes() isUserEntitlementsConfig_OneofKickstarterEyes {
	if m != nil {
		return m.OneofKickstarterEyes
	}
	return nil
}

func (m *UserEntitlementsConfig) GetKickstarterEyes() bool {
	if x, ok := m.GetOneofKickstarterEyes().(*UserEntitlementsConfig_KickstarterEyes); ok {
		return x.KickstarterEyes
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UserEntitlementsConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UserEntitlementsConfig_OneofMarshaler, _UserEntitlementsConfig_OneofUnmarshaler, _UserEntitlementsConfig_OneofSizer, []interface{}{
		(*UserEntitlementsConfig_KickstarterEyes)(nil),
	}
}

func _UserEntitlementsConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UserEntitlementsConfig)
	// oneof_kickstarter_eyes
	switch x := m.OneofKickstarterEyes.(type) {
	case *UserEntitlementsConfig_KickstarterEyes:
		t := uint64(0)
		if x.KickstarterEyes {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("UserEntitlementsConfig.OneofKickstarterEyes has unexpected type %T", x)
	}
	return nil
}

func _UserEntitlementsConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UserEntitlementsConfig)
	switch tag {
	case 1: // oneof_kickstarter_eyes.kickstarter_eyes
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofKickstarterEyes = &UserEntitlementsConfig_KickstarterEyes{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _UserEntitlementsConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UserEntitlementsConfig)
	// oneof_kickstarter_eyes
	switch x := m.OneofKickstarterEyes.(type) {
	case *UserEntitlementsConfig_KickstarterEyes:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Jdoc struct {
	DocVersion           uint64   `protobuf:"varint,1,opt,name=doc_version,json=docVersion" json:"doc_version,omitempty"`
	FmtVersion           uint64   `protobuf:"varint,2,opt,name=fmt_version,json=fmtVersion" json:"fmt_version,omitempty"`
	ClientMetadata       string   `protobuf:"bytes,3,opt,name=client_metadata,json=clientMetadata" json:"client_metadata,omitempty"`
	JsonDoc              string   `protobuf:"bytes,4,opt,name=json_doc,json=jsonDoc" json:"json_doc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jdoc) Reset()         { *m = Jdoc{} }
func (m *Jdoc) String() string { return proto.CompactTextString(m) }
func (*Jdoc) ProtoMessage()    {}
func (*Jdoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{4}
}
func (m *Jdoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jdoc.Unmarshal(m, b)
}
func (m *Jdoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jdoc.Marshal(b, m, deterministic)
}
func (dst *Jdoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jdoc.Merge(dst, src)
}
func (m *Jdoc) XXX_Size() int {
	return xxx_messageInfo_Jdoc.Size(m)
}
func (m *Jdoc) XXX_DiscardUnknown() {
	xxx_messageInfo_Jdoc.DiscardUnknown(m)
}

var xxx_messageInfo_Jdoc proto.InternalMessageInfo

func (m *Jdoc) GetDocVersion() uint64 {
	if m != nil {
		return m.DocVersion
	}
	return 0
}

func (m *Jdoc) GetFmtVersion() uint64 {
	if m != nil {
		return m.FmtVersion
	}
	return 0
}

func (m *Jdoc) GetClientMetadata() string {
	if m != nil {
		return m.ClientMetadata
	}
	return ""
}

func (m *Jdoc) GetJsonDoc() string {
	if m != nil {
		return m.JsonDoc
	}
	return ""
}

type NamedJdoc struct {
	JdocType             JdocType `protobuf:"varint,1,opt,name=jdoc_type,json=jdocType,enum=Anki.Vector.external_interface.JdocType" json:"jdoc_type,omitempty"`
	Doc                  *Jdoc    `protobuf:"bytes,2,opt,name=doc" json:"doc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedJdoc) Reset()         { *m = NamedJdoc{} }
func (m *NamedJdoc) String() string { return proto.CompactTextString(m) }
func (*NamedJdoc) ProtoMessage()    {}
func (*NamedJdoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{5}
}
func (m *NamedJdoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedJdoc.Unmarshal(m, b)
}
func (m *NamedJdoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedJdoc.Marshal(b, m, deterministic)
}
func (dst *NamedJdoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedJdoc.Merge(dst, src)
}
func (m *NamedJdoc) XXX_Size() int {
	return xxx_messageInfo_NamedJdoc.Size(m)
}
func (m *NamedJdoc) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedJdoc.DiscardUnknown(m)
}

var xxx_messageInfo_NamedJdoc proto.InternalMessageInfo

func (m *NamedJdoc) GetJdocType() JdocType {
	if m != nil {
		return m.JdocType
	}
	return JdocType_ROBOT_SETTINGS
}

func (m *NamedJdoc) GetDoc() *Jdoc {
	if m != nil {
		return m.Doc
	}
	return nil
}

type PullJdocsRequest struct {
	JdocTypes            []JdocType `protobuf:"varint,1,rep,packed,name=jdoc_types,json=jdocTypes,enum=Anki.Vector.external_interface.JdocType" json:"jdoc_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PullJdocsRequest) Reset()         { *m = PullJdocsRequest{} }
func (m *PullJdocsRequest) String() string { return proto.CompactTextString(m) }
func (*PullJdocsRequest) ProtoMessage()    {}
func (*PullJdocsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{6}
}
func (m *PullJdocsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullJdocsRequest.Unmarshal(m, b)
}
func (m *PullJdocsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullJdocsRequest.Marshal(b, m, deterministic)
}
func (dst *PullJdocsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullJdocsRequest.Merge(dst, src)
}
func (m *PullJdocsRequest) XXX_Size() int {
	return xxx_messageInfo_PullJdocsRequest.Size(m)
}
func (m *PullJdocsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullJdocsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullJdocsRequest proto.InternalMessageInfo

func (m *PullJdocsRequest) GetJdocTypes() []JdocType {
	if m != nil {
		return m.JdocTypes
	}
	return nil
}

type PullJdocsResponse struct {
	Status               *ResponseStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	NamedJdocs           []*NamedJdoc    `protobuf:"bytes,2,rep,name=named_jdocs,json=namedJdocs" json:"named_jdocs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PullJdocsResponse) Reset()         { *m = PullJdocsResponse{} }
func (m *PullJdocsResponse) String() string { return proto.CompactTextString(m) }
func (*PullJdocsResponse) ProtoMessage()    {}
func (*PullJdocsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{7}
}
func (m *PullJdocsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullJdocsResponse.Unmarshal(m, b)
}
func (m *PullJdocsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullJdocsResponse.Marshal(b, m, deterministic)
}
func (dst *PullJdocsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullJdocsResponse.Merge(dst, src)
}
func (m *PullJdocsResponse) XXX_Size() int {
	return xxx_messageInfo_PullJdocsResponse.Size(m)
}
func (m *PullJdocsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullJdocsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullJdocsResponse proto.InternalMessageInfo

func (m *PullJdocsResponse) GetStatus() *ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PullJdocsResponse) GetNamedJdocs() []*NamedJdoc {
	if m != nil {
		return m.NamedJdocs
	}
	return nil
}

type UpdateSettingsRequest struct {
	Settings             *RobotSettingsConfig `protobuf:"bytes,1,opt,name=settings" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateSettingsRequest) Reset()         { *m = UpdateSettingsRequest{} }
func (m *UpdateSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSettingsRequest) ProtoMessage()    {}
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{8}
}
func (m *UpdateSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSettingsRequest.Unmarshal(m, b)
}
func (m *UpdateSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSettingsRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSettingsRequest.Merge(dst, src)
}
func (m *UpdateSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSettingsRequest.Size(m)
}
func (m *UpdateSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSettingsRequest proto.InternalMessageInfo

func (m *UpdateSettingsRequest) GetSettings() *RobotSettingsConfig {
	if m != nil {
		return m.Settings
	}
	return nil
}

type UpdateSettingsResponse struct {
	Status               *ResponseStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Code                 ResultCode      `protobuf:"varint,2,opt,name=code,enum=Anki.Vector.external_interface.ResultCode" json:"code,omitempty"`
	Doc                  *Jdoc           `protobuf:"bytes,3,opt,name=doc" json:"doc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateSettingsResponse) Reset()         { *m = UpdateSettingsResponse{} }
func (m *UpdateSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSettingsResponse) ProtoMessage()    {}
func (*UpdateSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{9}
}
func (m *UpdateSettingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSettingsResponse.Unmarshal(m, b)
}
func (m *UpdateSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSettingsResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSettingsResponse.Merge(dst, src)
}
func (m *UpdateSettingsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSettingsResponse.Size(m)
}
func (m *UpdateSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSettingsResponse proto.InternalMessageInfo

func (m *UpdateSettingsResponse) GetStatus() *ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpdateSettingsResponse) GetCode() ResultCode {
	if m != nil {
		return m.Code
	}
	return ResultCode_SETTINGS_ACCEPTED
}

func (m *UpdateSettingsResponse) GetDoc() *Jdoc {
	if m != nil {
		return m.Doc
	}
	return nil
}

type UpdateAccountSettingsRequest struct {
	AccountSettings      *AccountSettingsConfig `protobuf:"bytes,1,opt,name=account_settings,json=accountSettings" json:"account_settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpdateAccountSettingsRequest) Reset()         { *m = UpdateAccountSettingsRequest{} }
func (m *UpdateAccountSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountSettingsRequest) ProtoMessage()    {}
func (*UpdateAccountSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{10}
}
func (m *UpdateAccountSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountSettingsRequest.Unmarshal(m, b)
}
func (m *UpdateAccountSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountSettingsRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAccountSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountSettingsRequest.Merge(dst, src)
}
func (m *UpdateAccountSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountSettingsRequest.Size(m)
}
func (m *UpdateAccountSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountSettingsRequest proto.InternalMessageInfo

func (m *UpdateAccountSettingsRequest) GetAccountSettings() *AccountSettingsConfig {
	if m != nil {
		return m.AccountSettings
	}
	return nil
}

type UpdateAccountSettingsResponse struct {
	Status               *ResponseStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Code                 ResultCode      `protobuf:"varint,2,opt,name=code,enum=Anki.Vector.external_interface.ResultCode" json:"code,omitempty"`
	Doc                  *Jdoc           `protobuf:"bytes,3,opt,name=doc" json:"doc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateAccountSettingsResponse) Reset()         { *m = UpdateAccountSettingsResponse{} }
func (m *UpdateAccountSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountSettingsResponse) ProtoMessage()    {}
func (*UpdateAccountSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{11}
}
func (m *UpdateAccountSettingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountSettingsResponse.Unmarshal(m, b)
}
func (m *UpdateAccountSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountSettingsResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateAccountSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountSettingsResponse.Merge(dst, src)
}
func (m *UpdateAccountSettingsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountSettingsResponse.Size(m)
}
func (m *UpdateAccountSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountSettingsResponse proto.InternalMessageInfo

func (m *UpdateAccountSettingsResponse) GetStatus() *ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpdateAccountSettingsResponse) GetCode() ResultCode {
	if m != nil {
		return m.Code
	}
	return ResultCode_SETTINGS_ACCEPTED
}

func (m *UpdateAccountSettingsResponse) GetDoc() *Jdoc {
	if m != nil {
		return m.Doc
	}
	return nil
}

type UpdateUserEntitlementsRequest struct {
	UserEntitlements     *UserEntitlementsConfig `protobuf:"bytes,1,opt,name=user_entitlements,json=userEntitlements" json:"user_entitlements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateUserEntitlementsRequest) Reset()         { *m = UpdateUserEntitlementsRequest{} }
func (m *UpdateUserEntitlementsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserEntitlementsRequest) ProtoMessage()    {}
func (*UpdateUserEntitlementsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{12}
}
func (m *UpdateUserEntitlementsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserEntitlementsRequest.Unmarshal(m, b)
}
func (m *UpdateUserEntitlementsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserEntitlementsRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserEntitlementsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserEntitlementsRequest.Merge(dst, src)
}
func (m *UpdateUserEntitlementsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserEntitlementsRequest.Size(m)
}
func (m *UpdateUserEntitlementsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserEntitlementsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserEntitlementsRequest proto.InternalMessageInfo

func (m *UpdateUserEntitlementsRequest) GetUserEntitlements() *UserEntitlementsConfig {
	if m != nil {
		return m.UserEntitlements
	}
	return nil
}

type UpdateUserEntitlementsResponse struct {
	Status               *ResponseStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Code                 ResultCode      `protobuf:"varint,2,opt,name=code,enum=Anki.Vector.external_interface.ResultCode" json:"code,omitempty"`
	Doc                  *Jdoc           `protobuf:"bytes,3,opt,name=doc" json:"doc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateUserEntitlementsResponse) Reset()         { *m = UpdateUserEntitlementsResponse{} }
func (m *UpdateUserEntitlementsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserEntitlementsResponse) ProtoMessage()    {}
func (*UpdateUserEntitlementsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{13}
}
func (m *UpdateUserEntitlementsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserEntitlementsResponse.Unmarshal(m, b)
}
func (m *UpdateUserEntitlementsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserEntitlementsResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUserEntitlementsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserEntitlementsResponse.Merge(dst, src)
}
func (m *UpdateUserEntitlementsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserEntitlementsResponse.Size(m)
}
func (m *UpdateUserEntitlementsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserEntitlementsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserEntitlementsResponse proto.InternalMessageInfo

func (m *UpdateUserEntitlementsResponse) GetStatus() *ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpdateUserEntitlementsResponse) GetCode() ResultCode {
	if m != nil {
		return m.Code
	}
	return ResultCode_SETTINGS_ACCEPTED
}

func (m *UpdateUserEntitlementsResponse) GetDoc() *Jdoc {
	if m != nil {
		return m.Doc
	}
	return nil
}

type JdocsChanged struct {
	JdocTypes            []JdocType `protobuf:"varint,1,rep,packed,name=jdoc_types,json=jdocTypes,enum=Anki.Vector.external_interface.JdocType" json:"jdoc_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JdocsChanged) Reset()         { *m = JdocsChanged{} }
func (m *JdocsChanged) String() string { return proto.CompactTextString(m) }
func (*JdocsChanged) ProtoMessage()    {}
func (*JdocsChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_settings_e4f4d050c56bd944, []int{14}
}
func (m *JdocsChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JdocsChanged.Unmarshal(m, b)
}
func (m *JdocsChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JdocsChanged.Marshal(b, m, deterministic)
}
func (dst *JdocsChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JdocsChanged.Merge(dst, src)
}
func (m *JdocsChanged) XXX_Size() int {
	return xxx_messageInfo_JdocsChanged.Size(m)
}
func (m *JdocsChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_JdocsChanged.DiscardUnknown(m)
}

var xxx_messageInfo_JdocsChanged proto.InternalMessageInfo

func (m *JdocsChanged) GetJdocTypes() []JdocType {
	if m != nil {
		return m.JdocTypes
	}
	return nil
}

func init() {
	proto.RegisterType((*CustomEyeColor)(nil), "Anki.Vector.external_interface.CustomEyeColor")
	proto.RegisterType((*RobotSettingsConfig)(nil), "Anki.Vector.external_interface.RobotSettingsConfig")
	proto.RegisterType((*AccountSettingsConfig)(nil), "Anki.Vector.external_interface.AccountSettingsConfig")
	proto.RegisterType((*UserEntitlementsConfig)(nil), "Anki.Vector.external_interface.UserEntitlementsConfig")
	proto.RegisterType((*Jdoc)(nil), "Anki.Vector.external_interface.Jdoc")
	proto.RegisterType((*NamedJdoc)(nil), "Anki.Vector.external_interface.NamedJdoc")
	proto.RegisterType((*PullJdocsRequest)(nil), "Anki.Vector.external_interface.PullJdocsRequest")
	proto.RegisterType((*PullJdocsResponse)(nil), "Anki.Vector.external_interface.PullJdocsResponse")
	proto.RegisterType((*UpdateSettingsRequest)(nil), "Anki.Vector.external_interface.UpdateSettingsRequest")
	proto.RegisterType((*UpdateSettingsResponse)(nil), "Anki.Vector.external_interface.UpdateSettingsResponse")
	proto.RegisterType((*UpdateAccountSettingsRequest)(nil), "Anki.Vector.external_interface.UpdateAccountSettingsRequest")
	proto.RegisterType((*UpdateAccountSettingsResponse)(nil), "Anki.Vector.external_interface.UpdateAccountSettingsResponse")
	proto.RegisterType((*UpdateUserEntitlementsRequest)(nil), "Anki.Vector.external_interface.UpdateUserEntitlementsRequest")
	proto.RegisterType((*UpdateUserEntitlementsResponse)(nil), "Anki.Vector.external_interface.UpdateUserEntitlementsResponse")
	proto.RegisterType((*JdocsChanged)(nil), "Anki.Vector.external_interface.JdocsChanged")
	proto.RegisterEnum("Anki.Vector.external_interface.ApiVersion", ApiVersion_name, ApiVersion_value)
	proto.RegisterEnum("Anki.Vector.external_interface.Volume", Volume_name, Volume_value)
	proto.RegisterEnum("Anki.Vector.external_interface.JdocType", JdocType_name, JdocType_value)
	proto.RegisterEnum("Anki.Vector.external_interface.JdocResolveMethod", JdocResolveMethod_name, JdocResolveMethod_value)
	proto.RegisterEnum("Anki.Vector.external_interface.RobotSetting", RobotSetting_name, RobotSetting_value)
	proto.RegisterEnum("Anki.Vector.external_interface.EyeColor", EyeColor_name, EyeColor_value)
	proto.RegisterEnum("Anki.Vector.external_interface.ButtonWakeWord", ButtonWakeWord_name, ButtonWakeWord_value)
	proto.RegisterEnum("Anki.Vector.external_interface.AccountSetting", AccountSetting_name, AccountSetting_value)
	proto.RegisterEnum("Anki.Vector.external_interface.UserEntitlement", UserEntitlement_name, UserEntitlement_value)
	proto.RegisterEnum("Anki.Vector.external_interface.ResultCode", ResultCode_name, ResultCode_value)
}

func init() { proto.RegisterFile("settings.proto", fileDescriptor_settings_e4f4d050c56bd944) }

var fileDescriptor_settings_e4f4d050c56bd944 = []byte{
	// 1531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0x4f, 0x6f, 0xe3, 0xc6,
	0x15, 0x17, 0x25, 0x59, 0x96, 0x9e, 0x6d, 0x69, 0x3c, 0xbb, 0x76, 0x95, 0x45, 0xb2, 0x59, 0x08,
	0x69, 0xe2, 0x28, 0x80, 0x0f, 0xce, 0x9f, 0x4b, 0x81, 0x02, 0x14, 0x3d, 0x96, 0x98, 0xa5, 0x48,
	0x61, 0x48, 0xd9, 0x71, 0x5a, 0x60, 0x4a, 0x93, 0xe3, 0xb5, 0xd6, 0x12, 0x47, 0x25, 0x47, 0x9b,
	0xba, 0xa7, 0x1e, 0x7a, 0x2a, 0x7a, 0xe8, 0xb7, 0xe8, 0xa1, 0xe8, 0x27, 0xe9, 0x17, 0xe8, 0xad,
	0xfd, 0x28, 0xc5, 0xf0, 0x8f, 0x6c, 0x31, 0x9b, 0x7a, 0x03, 0xe4, 0x94, 0x1b, 0xe7, 0xf7, 0xe6,
	0xbd, 0xf9, 0xbd, 0xdf, 0xcc, 0xbc, 0x79, 0x84, 0x76, 0xc2, 0xa5, 0x9c, 0x45, 0xaf, 0x92, 0xe3,
	0x65, 0x2c, 0xa4, 0xc0, 0xcf, 0xf5, 0xe8, 0x76, 0x76, 0x7c, 0xce, 0x03, 0x29, 0xe2, 0x63, 0xfe,
	0x07, 0xc9, 0xe3, 0xc8, 0x9f, 0xb3, 0x59, 0x24, 0x79, 0x7c, 0xed, 0x07, 0xfc, 0xd9, 0x41, 0xcc,
	0x93, 0xa5, 0x88, 0x12, 0xce, 0x12, 0xe9, 0xcb, 0x55, 0xee, 0xd6, 0xfb, 0x2d, 0xb4, 0x8d, 0x55,
	0x22, 0xc5, 0x82, 0xdc, 0x71, 0x43, 0xcc, 0x45, 0x8c, 0x11, 0xd4, 0x6e, 0x56, 0xbc, 0xab, 0xbd,
	0xd0, 0x8e, 0xaa, 0x54, 0x7d, 0xe2, 0xe7, 0x00, 0x89, 0x2f, 0x57, 0xb1, 0x2f, 0x67, 0x22, 0xea,
	0x56, 0x53, 0xc3, 0x03, 0x04, 0x77, 0x61, 0x9b, 0x47, 0xfe, 0xd5, 0x9c, 0x87, 0xdd, 0xda, 0x0b,
	0xed, 0xa8, 0x49, 0x8b, 0x61, 0xef, 0x9f, 0x0d, 0x78, 0x42, 0xc5, 0x95, 0x90, 0x6e, 0x4e, 0xd6,
	0x10, 0xd1, 0xf5, 0xec, 0x15, 0xfe, 0x08, 0xf6, 0x82, 0xb9, 0x08, 0x6e, 0xd9, 0xc9, 0x17, 0xec,
	0x46, 0xac, 0xe2, 0x74, 0xb5, 0xe6, 0xa8, 0x42, 0x77, 0x52, 0xf8, 0xe4, 0x8b, 0x91, 0x58, 0xc5,
	0x78, 0x08, 0x2d, 0x7e, 0xc7, 0x59, 0xa0, 0x68, 0xa5, 0xcb, 0xb6, 0x4f, 0x8e, 0x8e, 0xff, 0x7f,
	0x9a, 0xc7, 0x45, 0x1a, 0x23, 0x8d, 0x36, 0x79, 0x91, 0xd2, 0xb7, 0x80, 0x82, 0x34, 0x49, 0x76,
	0x1f, 0x4f, 0x31, 0xdd, 0x39, 0x39, 0x7e, 0x2c, 0xde, 0xa6, 0x38, 0xa3, 0x2a, 0x6d, 0x07, 0x9b,
	0x72, 0x7d, 0x06, 0x28, 0xe4, 0xd7, 0xfe, 0x6a, 0x2e, 0xd9, 0x5c, 0x04, 0x99, 0x44, 0xf5, 0x17,
	0xda, 0x51, 0x6b, 0x54, 0xa3, 0x9d, 0xdc, 0x62, 0xe5, 0x06, 0xfc, 0x31, 0xb4, 0xc3, 0x59, 0x22,
	0xd9, 0x2c, 0x61, 0x0b, 0x2e, 0xe3, 0x59, 0xd0, 0xdd, 0x4a, 0x13, 0xaf, 0xd3, 0x5d, 0x85, 0x9b,
	0xc9, 0x38, 0x45, 0x71, 0x17, 0x1a, 0x2a, 0xd8, 0x9c, 0x77, 0x1b, 0x69, 0xa8, 0x2d, 0x9a, 0x8f,
	0xf1, 0x18, 0xf6, 0x16, 0x7e, 0x22, 0x79, 0xcc, 0xde, 0x88, 0xf9, 0x6a, 0xc1, 0xbb, 0xdb, 0xa9,
	0x2e, 0x1f, 0x3f, 0x96, 0xc7, 0x79, 0x3a, 0x7b, 0xd4, 0xa0, 0xbb, 0x99, 0x7b, 0x36, 0xc6, 0xc7,
	0x80, 0x25, 0x5f, 0x2c, 0x15, 0xa1, 0x6b, 0xff, 0x26, 0xe6, 0xd1, 0x0d, 0x9f, 0xc9, 0x6e, 0x33,
	0x25, 0xb5, 0x4d, 0x91, 0xb2, 0x99, 0xc9, 0xd9, 0xda, 0x82, 0x3f, 0x80, 0x96, 0x9c, 0x2d, 0x38,
	0xfb, 0xa3, 0x88, 0x78, 0xb7, 0x95, 0x72, 0x6b, 0xd2, 0xa6, 0x82, 0xbe, 0x15, 0x11, 0xc7, 0x97,
	0xd0, 0xb9, 0x5a, 0x49, 0x29, 0x22, 0xf6, 0x9d, 0x7f, 0xcb, 0xbf, 0x13, 0x71, 0xd8, 0x85, 0x94,
	0xdf, 0xa3, 0x3a, 0x0f, 0x52, 0xb7, 0x0b, 0xff, 0x96, 0x5f, 0x88, 0x38, 0x1c, 0xb5, 0x68, 0xfb,
	0x6a, 0x8d, 0xa8, 0x38, 0x83, 0x03, 0x78, 0x22, 0x22, 0x2e, 0xae, 0xd9, 0xc6, 0xc1, 0x19, 0xec,
	0x43, 0x27, 0x83, 0xd7, 0x3b, 0x3b, 0xe8, 0xc2, 0x61, 0x3e, 0xb3, 0xb4, 0xe7, 0xf7, 0x96, 0xf2,
	0x8e, 0x0d, 0x0e, 0xe1, 0x69, 0x6e, 0xd9, 0xd8, 0x9e, 0x41, 0x1b, 0x76, 0x33, 0x3c, 0x93, 0xff,
	0x9e, 0xc5, 0xc6, 0x26, 0x0c, 0x9e, 0x41, 0x37, 0x83, 0xbf, 0x2f, 0xe6, 0x3d, 0xc3, 0xb5, 0x70,
	0x83, 0x5f, 0xc0, 0x41, 0x06, 0x95, 0xc4, 0xea, 0xfd, 0x4d, 0x83, 0x03, 0x3d, 0x08, 0xc4, 0x2a,
	0x2a, 0xdf, 0x98, 0x4f, 0xa1, 0x13, 0xfa, 0xd2, 0x57, 0x89, 0xcc, 0x79, 0x90, 0x9e, 0xb2, 0xe2,
	0xce, 0xb4, 0x95, 0xc1, 0x58, 0xe3, 0xf8, 0x43, 0x00, 0x7f, 0xb9, 0xcc, 0x19, 0xa7, 0xf7, 0xa6,
	0x35, 0xd2, 0x68, 0xcb, 0x5f, 0x2e, 0xad, 0x2c, 0x89, 0xf5, 0xf2, 0xa5, 0x88, 0x03, 0x0c, 0x28,
	0x33, 0xdc, 0xfb, 0xf7, 0x18, 0x1c, 0x4e, 0x13, 0x1e, 0x93, 0x48, 0xce, 0xe4, 0x9c, 0x2f, 0x78,
	0x24, 0x0b, 0x4a, 0x9f, 0x01, 0xba, 0x9d, 0x05, 0xb7, 0x89, 0xf4, 0x63, 0x25, 0x05, 0xbf, 0xe3,
	0xc9, 0x9a, 0x53, 0xe7, 0x81, 0x85, 0xdc, 0xf1, 0xe4, 0x5e, 0xfa, 0xb2, 0x4b, 0xef, 0xaf, 0x1a,
	0xd4, 0xbf, 0x0e, 0x45, 0x80, 0x3f, 0x84, 0x9d, 0x50, 0x04, 0xec, 0x0d, 0x8f, 0x93, 0x22, 0xbd,
	0x3a, 0x85, 0x50, 0x04, 0xe7, 0x19, 0xa2, 0x26, 0x5c, 0x2f, 0xe4, 0x7a, 0x42, 0x35, 0x9b, 0x70,
	0xbd, 0x90, 0xc5, 0x84, 0x4f, 0xa0, 0x13, 0xcc, 0x67, 0x3c, 0x92, 0x6a, 0xfb, 0x7c, 0x95, 0x5d,
	0x7a, 0xcd, 0x5b, 0xb4, 0x9d, 0xc1, 0xe3, 0x1c, 0xc5, 0xef, 0x41, 0xf3, 0x75, 0x22, 0x22, 0x16,
	0x8a, 0x20, 0xbb, 0xac, 0x74, 0x5b, 0x8d, 0x4f, 0x45, 0xd0, 0xfb, 0x8b, 0x06, 0x2d, 0xdb, 0x5f,
	0xf0, 0x30, 0xe5, 0x44, 0xa0, 0xf5, 0x5a, 0x91, 0x92, 0x77, 0xcb, 0xac, 0x24, 0xbe, 0x43, 0x09,
	0x52, 0x8e, 0xde, 0xdd, 0x92, 0xd3, 0xe6, 0xeb, 0xfc, 0x0b, 0x7f, 0x05, 0x35, 0xb5, 0x54, 0x35,
	0xad, 0x39, 0x1f, 0xbd, 0x4b, 0x00, 0xaa, 0x1c, 0x7a, 0xbf, 0x01, 0x34, 0x59, 0xcd, 0xe7, 0x0a,
	0x48, 0x28, 0xff, 0xfd, 0x8a, 0x27, 0x12, 0x0f, 0x01, 0xd6, 0x94, 0x94, 0xe0, 0xb5, 0x1f, 0xc5,
	0xa9, 0x55, 0x70, 0x4a, 0x7a, 0x7f, 0xd7, 0x60, 0xff, 0x41, 0xf4, 0xec, 0x75, 0xc0, 0x67, 0xd0,
	0xc8, 0x1e, 0x88, 0x34, 0xdd, 0x77, 0xa8, 0x90, 0x85, 0xa7, 0x9b, 0x7a, 0xd1, 0xdc, 0x1b, 0x7f,
	0x0d, 0x3b, 0x91, 0x92, 0x91, 0xa9, 0x05, 0x93, 0x6e, 0xf5, 0x45, 0xed, 0x68, 0xe7, 0xe4, 0xd3,
	0xc7, 0x82, 0xad, 0x95, 0xa7, 0x10, 0x15, 0x9f, 0x49, 0xef, 0x06, 0x0e, 0xa6, 0xcb, 0xd0, 0x97,
	0xbc, 0xb8, 0x14, 0x85, 0x16, 0x0e, 0x34, 0x8b, 0x67, 0x30, 0xa7, 0xfb, 0xf9, 0xa3, 0x74, 0xbf,
	0xff, 0x1c, 0xd1, 0x75, 0x90, 0xde, 0xbf, 0x35, 0x38, 0x2c, 0x2f, 0xf5, 0x13, 0x0b, 0xf3, 0x6b,
	0xa8, 0x07, 0x22, 0xe4, 0xf9, 0x83, 0xd6, 0x7f, 0x87, 0x28, 0xab, 0xb9, 0x34, 0x44, 0xc8, 0x69,
	0xea, 0x57, 0x9c, 0xa5, 0xda, 0x8f, 0x3d, 0x4b, 0x7f, 0xd2, 0xe0, 0xfd, 0x2c, 0xb5, 0x52, 0x85,
	0x29, 0xc4, 0xfc, 0x1d, 0x20, 0x3f, 0xb3, 0xb0, 0x92, 0xa8, 0x5f, 0x3e, 0xb6, 0xca, 0x5b, 0x6b,
	0x16, 0xed, 0xf8, 0x9b, 0x70, 0xef, 0x3f, 0x1a, 0x7c, 0xf0, 0x03, 0x14, 0x7e, 0x26, 0x22, 0xff,
	0x79, 0x9d, 0x61, 0xb9, 0x68, 0x16, 0x2a, 0x07, 0xb0, 0xbf, 0x4a, 0x54, 0xed, 0x7b, 0x60, 0xcb,
	0x93, 0xfd, 0xea, 0xb1, 0x75, 0xde, 0x5e, 0x88, 0x29, 0x5a, 0x95, 0xf0, 0xde, 0x7f, 0x35, 0x78,
	0xfe, 0x43, 0x34, 0x7e, 0x26, 0x4a, 0x5f, 0xc0, 0x6e, 0x5a, 0x1c, 0x8c, 0x1b, 0x3f, 0x7a, 0xc5,
	0xc3, 0x9f, 0xac, 0x2c, 0xf6, 0x7f, 0x09, 0xa0, 0x2f, 0x67, 0xc5, 0x93, 0xb2, 0x03, 0xdb, 0xa6,
	0x7d, 0xae, 0x5b, 0xe6, 0x29, 0xaa, 0x60, 0x80, 0x86, 0xa5, 0x7b, 0xc4, 0xf5, 0x90, 0xd6, 0xa7,
	0xd0, 0xc8, 0x7b, 0xa8, 0x26, 0xd4, 0xc7, 0x53, 0x8f, 0xa0, 0x0a, 0xde, 0x86, 0x9a, 0xe5, 0x5c,
	0x20, 0x0d, 0xb7, 0x01, 0xc6, 0xe4, 0xd4, 0x9c, 0x8e, 0x99, 0x1a, 0x57, 0x95, 0x63, 0x36, 0x46,
	0x35, 0xdc, 0x81, 0x9d, 0xdc, 0x36, 0x32, 0x87, 0x23, 0x54, 0x57, 0xfe, 0xe9, 0xd7, 0x56, 0x9f,
	0x43, 0xb3, 0x60, 0x84, 0x31, 0xb4, 0xa9, 0x33, 0x70, 0x3c, 0xe6, 0x12, 0xcf, 0x33, 0xed, 0xa1,
	0x8b, 0x2a, 0xb8, 0x0b, 0x4f, 0x33, 0xcc, 0x32, 0xcf, 0x88, 0x67, 0x8e, 0x09, 0x73, 0x3d, 0xdd,
	0x73, 0x91, 0x86, 0x9f, 0x02, 0xd2, 0x0d, 0xc3, 0x99, 0xda, 0x0f, 0xe6, 0x57, 0xf1, 0x01, 0xec,
	0x4f, 0x5d, 0x42, 0x19, 0xb1, 0x3d, 0xd3, 0xb3, 0xc8, 0x98, 0xd8, 0x9e, 0x8b, 0x6a, 0xfd, 0x5f,
	0xc1, 0x7e, 0xaa, 0x23, 0x4f, 0xc4, 0xfc, 0x0d, 0x1f, 0x73, 0x79, 0x23, 0x42, 0xbc, 0x0f, 0x7b,
	0x93, 0xa9, 0x3b, 0x62, 0x9e, 0xc3, 0x0c, 0xcb, 0x99, 0xaa, 0x74, 0x9f, 0x40, 0x67, 0x32, 0xb5,
	0x2c, 0x76, 0x46, 0x9d, 0x71, 0x0e, 0x6a, 0xfd, 0x7f, 0x69, 0xb0, 0xfb, 0xb0, 0x86, 0x2a, 0xc7,
	0x8d, 0x96, 0x0c, 0x55, 0xf0, 0xde, 0x83, 0xc6, 0x3d, 0x23, 0x57, 0x6e, 0xc5, 0x50, 0x55, 0xa1,
	0xe5, 0x36, 0x0c, 0xd5, 0x54, 0xda, 0x9b, 0x2d, 0x18, 0xaa, 0x2b, 0xf5, 0xb2, 0x66, 0x04, 0x6d,
	0xa9, 0xd5, 0x36, 0x5a, 0x2f, 0xd4, 0xc0, 0x87, 0x6f, 0xeb, 0x61, 0xd1, 0xb6, 0x62, 0xb1, 0x6e,
	0xb9, 0x50, 0x53, 0x65, 0x53, 0x6a, 0xb7, 0x50, 0xab, 0xff, 0x0f, 0x0d, 0x9a, 0xeb, 0x56, 0x7e,
	0x1f, 0xf6, 0x3c, 0x73, 0xc2, 0x9c, 0x73, 0x42, 0x99, 0x47, 0x74, 0x0b, 0x55, 0x14, 0x1d, 0x35,
	0x3c, 0x33, 0x3d, 0xe6, 0x50, 0xdd, 0x1e, 0x12, 0xa4, 0x29, 0x6c, 0x6a, 0x1b, 0xba, 0x6d, 0x5f,
	0xb2, 0x4b, 0x62, 0x65, 0x1b, 0xfc, 0x04, 0x3a, 0xb6, 0x63, 0x33, 0xcb, 0xb4, 0x89, 0x4e, 0x99,
	0x65, 0x8e, 0x09, 0xaa, 0xa9, 0xed, 0x72, 0x4d, 0x7b, 0x38, 0xb5, 0x74, 0x6a, 0x7a, 0x97, 0xcc,
	0xd5, 0x27, 0x93, 0x91, 0x49, 0x09, 0xaa, 0xe3, 0xf7, 0xe0, 0xe0, 0x4c, 0xb7, 0x5c, 0xc2, 0x26,
	0x8e, 0x6b, 0x7a, 0xe6, 0x39, 0x61, 0x93, 0x29, 0x9d, 0x58, 0x04, 0x6d, 0xe1, 0x67, 0x70, 0x68,
	0x38, 0xf6, 0xd9, 0xd4, 0x35, 0x1d, 0x9b, 0x8d, 0x75, 0x8f, 0x9a, 0xdf, 0xb0, 0x21, 0x25, 0xc4,
	0x46, 0x8d, 0xfe, 0x4b, 0x68, 0x6f, 0xf6, 0xc9, 0xf8, 0x39, 0x3c, 0x1b, 0x4c, 0x3d, 0xcf, 0xb1,
	0xd9, 0x85, 0xfe, 0x92, 0x5c, 0x38, 0xf4, 0x94, 0x8d, 0xc8, 0x25, 0x3b, 0x27, 0x86, 0xe7, 0x50,
	0x54, 0x51, 0x0b, 0x95, 0xed, 0xba, 0x45, 0xbe, 0xd1, 0x91, 0xd6, 0xff, 0x12, 0xda, 0x9b, 0x55,
	0x58, 0x25, 0x71, 0xaa, 0x7b, 0x3a, 0x33, 0x1c, 0xcb, 0x22, 0x86, 0x67, 0x3a, 0x36, 0xaa, 0xa8,
	0xa3, 0xac, 0x4f, 0x26, 0xcc, 0x72, 0x0c, 0xdd, 0x22, 0x48, 0xeb, 0x7f, 0x02, 0x9d, 0x52, 0x4d,
	0x51, 0x3b, 0xf9, 0xd2, 0x34, 0x5e, 0xba, 0x9e, 0x4e, 0x3d, 0x75, 0xda, 0x2e, 0x89, 0x8b, 0x2a,
	0x7d, 0x1d, 0xe0, 0xfe, 0xb2, 0xab, 0xa3, 0x58, 0x1c, 0x4c, 0xa6, 0x1b, 0x06, 0x99, 0x78, 0x44,
	0x1d, 0xb1, 0xf7, 0xa1, 0x4b, 0x28, 0x75, 0x28, 0x9b, 0x4e, 0x4e, 0x75, 0x8f, 0x30, 0xd3, 0x66,
	0x13, 0xea, 0x0c, 0x29, 0x71, 0x5d, 0xa4, 0x5d, 0x35, 0xd2, 0x7f, 0xd4, 0xcf, 0xff, 0x17, 0x00,
	0x00, 0xff, 0xff, 0xbc, 0x46, 0xc3, 0x7d, 0xec, 0x0e, 0x00, 0x00,
}
